name: "Setup"
description: "Node setup and install"
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        registry-url: "https://registry.npmjs.org"
    - name: Cache NPM dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('package-lock.json') }}
    - name: Install npm packages
      run: |
        npm ci
      shell: bash
